using System.Collections;
using System.Collections.Generic;
using UnityEngine;

public class Tile : MonoBehaviour
{
    #region Attributes
    public TileTypes type; //The type of the tile
    public ProductionBuilding building; //The building on this tile
    public List<Tile> neighborTiles; //List of all surrounding tiles. Generated by GameManager
    public int coordinateHeight; //The coordinate on the y-axis on the tile grid (not world coordinates)
    public int coordinateWidth; //The coordinate on the x-axis on the tile grid (not world coordinates)
    public GameObject hideOnBuilding; //Contains all decoration that is disabled when building is placed
    #endregion

    #region Enumerations
    public enum TileTypes { Empty, Water, Sand, Grass, Forest, Stone, Mountain }; //Enumeration of all available tile types. Can be addressed from other scripts by calling Tile.Tiletypes
    #endregion

    //This class acts as a data container and has no functionality
}
